In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random

In [36]:
import tensorflow

In [113]:
df=pd.read_csv('C:\\Users\\NITJ\Downloads\\mnist_train.csv\\mnist_train.csv', delimiter=',', dtype=int)
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0          5    0    0    0    0    0    0    0    0    0  ...      0      0   
1          0    0    0    0    0    0    0    0    0    0  ...      0      0   
2          4    0    0    0    0    0    0    0    0    0  ...      0      0   
3          1    0    0    0    0    0    0    0    0    0  ...      0      0   
4          9    0    0    0    0    0    0    0    0    0  ...      0      0   
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
59995      8    0    0    0    0    0    0    0    0    0  ...      0      0   
59996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
59997      5    0    0    0    0    0    0    0    0    0  ...      0      0   
59998      6    0    0    0    0    0    0    0    0    0  ...      0      0   
59999      8    0    0    0    0    0    0    0    0    0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0          0      0      0      0      0      0      0      0  
1          0      0      0      0      0      0      0      0  
2          0      0      0      0      0      0      0      0  
3          0      0      0      0      0      0      0      0  
4          0      0      0      0      0      0      0      0  
...      ...    ...    ...    ...    ...    ...    ...    ...  
59995      0      0      0      0      0      0      0      0  
59996      0      0      0      0      0      0      0      0  
59997      0      0      0      0      0      0      0      0  
59998      0      0      0      0      0      0      0      0  
59999      0      0      0      0      0      0      0      0  

[60000 rows x 785 columns]

In [114]:
X = df.iloc[:, 1:].values
y = df.iloc[:, 0].values

In [136]:
# Normalize
X=X/255

In [137]:
y

array([5, 0, 4, ..., 5, 6, 8])

In [138]:
X.shape

(60000, 784)

In [139]:
X_train=X
y_train=y

In [140]:
pd.set_option("display.max_columns",20)
pd.set_option("display.max_rows",10)

In [141]:
pd.DataFrame(X_train)

0    1    2    3    4    5    6    7    8    9    ...  774  775  776  \
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...  0.0  0.0  0.0   

       777  778  779  780  781  782  783  
0      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4      0.0  0.0  0.0  0.0  0.0  0.0  0.0  
...    ...  ...  ...  ...  ...  ...  ...  
59995  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59997  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
59999  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[60000 rows x 784 columns]

In [142]:
# Part 2 - Now let's make the ANN!
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [143]:
# Create a new Sequential object
model = Sequential()

# Create the input layer and 1st hidden layer with 400 nodes
model.add(Dense(400,kernel_initializer ='uniform', activation = 'relu', input_dim = 784))

# Create another hidden layer with 100 nodes
model.add(Dense(100, activation="relu"))
          

# Create an output layer, 10 nodes
model.add(Dense(10, activation="softmax"))

# Compile model
model.compile(optimizer = 'adam' , loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [144]:
from keras.utils import np_utils
dummy_y=np_utils.to_categorical(y_train)
dummy_y

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [145]:
model.fit(X_train,dummy_y,batch_size = 10 ,nb_epoch=5)

C:\Users\NITJ\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/5
60000/60000 [==============================] - 31s 514us/step - loss: 0.1892 - accuracy: 0.9424
Epoch 2/5
60000/60000 [==============================] - 32s 528us/step - loss: 0.0878 - accuracy: 0.9728
Epoch 3/5
60000/60000 [==============================] - 33s 549us/step - loss: 0.0642 - accuracy: 0.9801
Epoch 4/5
60000/60000 [==============================] - 34s 573us/step - loss: 0.0473 - accuracy: 0.9857
Epoch 5/5
60000/60000 [==============================] - 34s 559us/step - loss: 0.0416 - accuracy: 0.9869


In [163]:
train_accuracy = model.evaluate(X_train, dummy_y)
print(train_accuracy[1])

60000/60000 [==============================] - 2s 38us/step
0.9926000237464905


In [158]:
# Input test data
df=pd.read_csv('C:\\Users\\NITJ\Downloads\\mnist_test.csv\\mnist_test.csv', delimiter=',', dtype=int)
df

label  1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  ...  28x19  28x20  \
0         7    0    0    0    0    0    0    0    0    0  ...      0      0   
1         2    0    0    0    0    0    0    0    0    0  ...      0      0   
2         1    0    0    0    0    0    0    0    0    0  ...      0      0   
3         0    0    0    0    0    0    0    0    0    0  ...      0      0   
4         4    0    0    0    0    0    0    0    0    0  ...      0      0   
...     ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...    ...   
9995      2    0    0    0    0    0    0    0    0    0  ...      0      0   
9996      3    0    0    0    0    0    0    0    0    0  ...      0      0   
9997      4    0    0    0    0    0    0    0    0    0  ...      0      0   
9998      5    0    0    0    0    0    0    0    0    0  ...      0      0   
9999      6    0    0    0    0    0    0    0    0    0  ...      0      0   

      28x21  28x22  28x23  28x24  28x25  28x26  28x27  28x28  
0         0      0      0      0      0      0      0      0  
1         0      0      0      0      0      0      0      0  
2         0      0      0      0      0      0      0      0  
3         0      0      0      0      0      0      0      0  
4         0      0      0      0      0      0      0      0  
...     ...    ...    ...    ...    ...    ...    ...    ...  
9995      0      0      0      0      0      0      0      0  
9996      0      0      0      0      0      0      0      0  
9997      0      0      0      0      0      0      0      0  
9998      0      0      0      0      0      0      0      0  
9999      0      0      0      0      0      0      0      0  

[10000 rows x 785 columns]

In [159]:
X_test = df.iloc[:, 1:].values
y_test = df.iloc[:, 0].values
X_test=X_test/255

In [160]:
y_pred=pd.DataFrame(model.predict(X_test)).idxmax(axis = 1).values
y_pred

array([7, 2, 1, ..., 4, 5, 6], dtype=int64)

In [161]:
y_test

array([7, 2, 1, ..., 4, 5, 6])

In [162]:
dummy_y_test=np_utils.to_categorical(y_test)
test_accuracy = model.evaluate(X_test, dummy_y_test)
print(test_accuracy[1])

10000/10000 [==============================] - 0s 38us/step
0.9789000153541565


In [154]:
np.unique(y_test)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])